name: Release to npm
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: https://npm.pkg.github.com/

      - name: Build for NPM
        run: deno run -A scripts/build-npm.ts

      - run: cd npm && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_PA_TOKEN}}
